### ISSUE TITLE
4chan X compatibility

### ISSUE THREAD

**Issue by lc-guy** [ihavenoface/dragonchan-userscript#5]
![https://qt.vidyagam.es/RTPkvox.png](https://qt.vidyagam.es/RTPkvox.png)
currently doesn't work

**Comment by ihavenoface** [comment]
Are you using 4chan via https?

**Comment by lc-guy** [comment]
Yep
I suppose that's why it isn't working?

edit: yep, seems to work through http. Sorry I'm retarded

**Comment by ihavenoface** [comment]
The issue here is that drgchan.ddns.net is not fetchable on https so the browser just bails out.

I'll reopen this issue for others to see.

**Comment by ihavenoface** [comment]
https should work now.
