### ISSUE TITLE
Download Link 404

### ISSUE THREAD

**Issue by Kellin-Myers** [ihavenoface/dragonchan-userscript#6]
Hello,

I have made sure I am not browsing 4chan in https, and whenever I click the link to install in the read.me, I get a 404 link.

**Comment by ihavenoface** [comment]
Looks like travis didn't build the last commit properly.
I kicked off a new one at https://travis-ci.org/ihavenoface/dragonchan-userscript/builds/232954939. Once that's done the link should work again.

**Comment by ihavenoface** [comment]
It's done actually.
